providers = ["java"]

[phases.setup]
nixPkgs = ["maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/dependency/webapp-runner.jar --port $PORT target/*.war"
